version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./cleaned_data:/data
    ports:
      - "5000:5000"

  dashboard:
    build: ./dashboard
    volumes:
      - ./cleaned_data:/data
    ports:
      - "8501:8501"
    depends_on:
      - api
  
